/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Attribute {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  name: string;
  organizationId: string;
  updatedAt: Generated<Timestamp>;
}

export interface AttributeOption {
  attributeId: string;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  organizationId: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface Invitation {
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: Generated<string>;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
}

export interface Member {
  createdAt: Timestamp;
  id: Generated<string>;
  organizationId: string;
  role: string;
  userId: string;
}

export interface Organization {
  createdAt: Timestamp;
  id: Generated<string>;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface Product {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  name: string;
  organizationId: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProductAttribute {
  attributeId: string;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  displayOrder: number;
  id: Generated<string>;
  organizationId: string;
  productId: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProductVariant {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  isActive: Generated<boolean>;
  organizationId: string;
  price: Generated<Numeric>;
  productId: string;
  sku: string;
  stockQuantity: Generated<number>;
  updatedAt: Generated<Timestamp>;
}

export interface Session {
  activeOrganizationId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface StockMovement {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  deletedAt: Timestamp | null;
  delta: number;
  id: Generated<string>;
  movementType: string;
  notes: string | null;
  organizationId: string;
  productId: string;
  productVariantId: string | null;
  referenceId: string | null;
  warehouseId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: Generated<string>;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface VariantOption {
  attributeOptionId: string;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  organizationId: string;
  productAttributeId: string;
  productVariantId: string;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface Warehouse {
  city: string | null;
  code: string;
  contactEmail: string | null;
  contactName: string | null;
  contactPhone: string | null;
  country: Generated<string>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  name: string;
  notes: string | null;
  organizationId: string;
  postalCode: string | null;
  province: string | null;
  streetAddress: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  account: Account;
  attribute: Attribute;
  attributeOption: AttributeOption;
  invitation: Invitation;
  member: Member;
  organization: Organization;
  product: Product;
  productAttribute: ProductAttribute;
  productVariant: ProductVariant;
  session: Session;
  stockMovement: StockMovement;
  user: User;
  variantOption: VariantOption;
  verification: Verification;
  warehouse: Warehouse;
}
