import {
  AlertTriangle,
  ArrowDownRight,
  ArrowLeftRight,
  ArrowUpFromLine,
  ArrowUpRight,
  LayoutDashboard,
  History,
  Minus,
  PackageOpen,
  Package,
  ShoppingCart,
  Settings,
  SlidersHorizontal,
  Tag,
  LogOut,
  User,
  Moon,
  Sun,
  Monitor,
  Calendar,
  ChevronRight,
  Building2,
  Warehouse,
  type LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  alert: AlertTriangle,
  arrowDownRight: ArrowDownRight,
  arrowLeftRight: ArrowLeftRight,
  arrowUpFromLine: ArrowUpFromLine,
  arrowUpRight: ArrowUpRight,
  calendar: Calendar,
  dashboard: LayoutDashboard,
  history: History,
  minus: Minus,
  products: Package,
  productTag: Tag,
  package: Package,
  packageOpen: PackageOpen,
  orders: ShoppingCart,
  slidersHorizontal: SlidersHorizontal,
  warehouse: Warehouse,
  settings: Settings,
  logout: LogOut,
  user: User,
  moon: Moon,
  sun: Sun,
  monitor: Monitor,
  chevronRight: ChevronRight,
  organization: Building2,
};
