import {
  AlertTriangle,
  ArrowDownRight,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpFromLine,
  ArrowUpRight,
  LayoutDashboard,
  History,
  Minus,
  Eye,
  Check,
  Circle,
  CreditCard,
  Loader2,
  PackageOpen,
  Package,
  Pencil,
  Plus,
  Search,
  ShoppingCart,
  Settings,
  SlidersHorizontal,
  Tag,
  Trash2,
  LogOut,
  User,
  X,
  Moon,
  Sun,
  Monitor,
  Calendar,
  ChevronRight,
  Building2,
  Warehouse,
  type LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  alert: AlertTriangle,
  arrowDownRight: ArrowDownRight,
  arrowLeft: ArrowLeft,
  arrowLeftRight: ArrowLeftRight,
  arrowRight: ArrowRight,
  arrowUpFromLine: ArrowUpFromLine,
  arrowUpRight: ArrowUpRight,
  calendar: Calendar,
  check: Check,
  circle: Circle,
  creditCard: CreditCard,
  dashboard: LayoutDashboard,
  eye: Eye,
  history: History,
  loader: Loader2,
  minus: Minus,
  pencil: Pencil,
  plus: Plus,
  products: Package,
  productTag: Tag,
  package: Package,
  packageOpen: PackageOpen,
  search: Search,
  orders: ShoppingCart,
  slidersHorizontal: SlidersHorizontal,
  trash: Trash2,
  warehouse: Warehouse,
  settings: Settings,
  logout: LogOut,
  user: User,
  x: X,
  moon: Moon,
  sun: Sun,
  monitor: Monitor,
  chevronRight: ChevronRight,
  organization: Building2,
};
