import type { Metadata } from "next";
import "@fontsource-variable/roboto";
import "./globals.css";

import { Toaster } from "@/shared/presentation/components/ui/sonner";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `try{const t=localStorage.getItem('theme');if(t==='dark'||t==='light'){document.documentElement.classList.add(t)}else if(window.matchMedia('(prefers-color-scheme: dark)').matches){document.documentElement.classList.add('dark')}}catch{}`,
          }}
        />
      </head>
      <body className="font-roboto">
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
