import type { Metadata } from "next";
import "@fontsource-variable/roboto";
import "./globals.css";

import { Toaster } from "@/shared/presentation/components/ui/sonner";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-roboto">
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
